sudo: required
services: 
 - docker
 
before_install:
 - docker build -t noneedrelax/react-test -f ./client/Dockerfile.dev ./client
 
script:
 - docker run noneedrelax/react-test npm run test -- --coverage
 
after_success:
 - docker build -t noneedrelax/multi-client ./client
 - docker build -t noneedrelax/multi-server ./server
 - docker build -t noneedrelax/multi-nginx ./nginx
 - docker build -t noneedrelax/multi-worker ./worker
 
 # Login to the docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 
 # Push the stuff
 - docker push noneedrelax/multi-client
 - docker push noneedrelax/multi-server
 - docker push noneedrelax/multi-nginx 
 - docker push noneedrelax/multi-worker
 
deploy: 
 provider: elasticbeanstalk
 region: us-west-2
 app: multi-docker
 env: MultiDocker-env
 bucket_name: elasticbeanstalk-us-west-2-563421743711
 bucket_path: docker-multi
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key:
  secure: $AWS_SECRET_KEY
  
