sudo: required
services: 
 - docker
 
before_install:
 - docker build -t noneedrelax/react-test -f ./client/Dockerfile.dev ./client
 
script:
 - docker run noneedrelax/react-test npm run test -- --coverage
 
after_success:
 - docker build -t noneedrelax/multi-client ./client
 - docker build -t noneedrelax/multi-server ./server
 - docker build -t noneedrelax/multi-nginx ./nginx
 - docker build -t noneedrelax/multi-worker./worker
 
 # Login to the docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 
 # Push the stuff
 - docker push -t noneedrelax/multi-client ./client
 - docker push -t noneedrelax/multi-server ./server
 - docker push -t noneedrelax/multi-nginx ./nginx
 - docker push -t noneedrelax/multi-worker./worker
